FROM mcr.microsoft.com/dotnet/sdk:10.0
WORKDIR /src

COPY . .

RUN dotnet restore
RUN dotnet tool install --global dotnet-ef --version 10.*

ENV PATH="$PATH:/root/.dotnet/tools"

CMD ["dotnet", "ef", "database", "update", "--project", "Encore.Api.csproj", "--startup-project", "Encore.Api.csproj"]
